export const WORKLOAD_TYPE_DEPLOYMENTS="Deployment"
export const WORKLOAD_TYPE_DEAEMONSET="Daemonset"
export const WORKLOAD_TYPE_STATEFULSETS="Statefulset"
export const WORKLOAD_TYPE_PODS="Pod"
export const WORKLOAD_TYPE_CRONJOBS="Cronjob"
export const WORKLOAD_TYPE_JOBS="Job"