name: KDD Build and Push

on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: "ratiel/kdd"

jobs:
  build_and_push:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
	  - name: run build 
      uses: ./.github/actions/build
      with:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        BUILD_NUMBER: ${{ github.run_number }}
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push ${{  env.IMAGE_NAME  }}:${{  github.run_number  }}
