name: PR Validator

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: "ratiel/kdd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run build
      uses: ./.github/actions/build
      with:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
        BUILD_NUMBER: ${{ github.run_number }}